'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) =>
    await queryInterface.bulkInsert('Books', [
      {
        id: 1,
        name: 'The Boston Girl',
        author: 'Anita Diamant',
        genre: 'Melodrama',
        price: 100,
        publishHouse: 'English hats',
        coverId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: 'The Cider House Rules',
        author: 'John Irving',
        genre: 'Romance',
        price: 121,
        publishHouse: 'English hats',
        coverId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: 'Olive Kitteridge',
        author: 'Elizabeth Strout',
        genre: 'Drama',
        price: 130,
        publishHouse: 'English hats',
        coverId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: 'We Love You, Charlie Freeman',
        author: 'Kaitlyn Greenidge',
        genre: 'Psychological realism',
        price: 141,
        publishHouse: 'English hats',
        coverId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: 'Ethan Frome',
        author: 'Edith Wharton',
        genre: 'Fantasy',
        price: 200,
        publishHouse: 'English hats',
        coverId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: 'Revolutionary Road',
        author: 'Richard Yates',
        genre: 'Romance',
        price: 199,
        publishHouse: 'Nipples production',
        coverId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: 'Empire Falls',
        author: 'Richard Russo',
        genre: 'Psychological realism',
        price: 299,
        publishHouse: 'Nipples production',
        coverId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: 'Main',
        author: 'J. Courtney Sullivan',
        genre: 'Humor',
        price: 229,
        publishHouse: 'Nipples production',
        coverId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: 'Wintergirls',
        author: 'Laurie Halse Anderson',
        genre: 'Novel',
        price: 391,
        publishHouse: 'Nipples production',
        coverId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: `The Pilot's Wife`,
        author: 'Anita Shreve',
        genre: 'Novel',
        price: 329,
        publishHouse: 'Nipples production',
        coverId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: 'Labor Day',
        author: 'Joyce Maynard',
        genre: 'Novel',
        price: 419,
        publishHouse: 'what England is silent about',
        coverId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        name: 'On Beauty',
        author: 'Zadie Smith',
        genre: 'Novel',
        price: 311,
        publishHouse: 'what England is silent about',
        coverId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        name: 'Faith',
        author: 'Jennifer Haigh',
        genre: 'Home fiction',
        price: 212,
        publishHouse: 'what England is silent about',
        coverId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        name: 'Hush, Hush',
        author: 'Becca Fitzpatrick',
        genre: 'Novel',
        price: 311,
        publishHouse: 'what England is silent about',
        coverId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        name: 'Interpreter of Maladies',
        author: 'Jhumpa Lahiri',
        genre: 'Story',
        price: 212,
        publishHouse: 'what England is silent about',
        coverId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        name: 'The Rules of Attraction',
        author: 'Bret Easton Ellis',
        genre: 'Novel',
        price: 199,
        publishHouse: 'tea with milk',
        coverId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        name: 'Infinite Jest',
        author: 'David Foster Wallace',
        genre: 'Humor',
        price: 299,
        publishHouse: 'tea with milk',
        coverId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        name: 'Strong Motion',
        author: 'Jonathan Franzen',
        genre: 'Fiction',
        price: 399,
        publishHouse: 'tea with milk',
        coverId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 19,
        name: 'Boy, Snow, Bird',
        author: 'Helen Oyeyemi',
        genre: 'Novel',
        price: 400,
        publishHouse: 'tea with milk',
        coverId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 20,
        name: 'The Bell Jar',
        author: 'Sylvia Plath',
        genre: 'Autobiography',
        price: 229,
        publishHouse: 'tea with milk',
        coverId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]),

  down: async (queryInterface, Sequelize) =>
    await queryInterface.bulkDelete('Books', null, {}),
};
