module.exports = {
  up: async (queryInterface, Sequelize) =>
    await queryInterface.bulkInsert('Books', [
      {
        id: 1,
        name: 'The Boston Girl',
        authorId: 1,
        price: 100,
        publishId: 1,
        coverId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: 'The Cider House Rules',
        authorId: 2,
        price: 121,
        publishId: 1,
        coverId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: 'Olive Kitteridge',
        authorId: 3,
        price: 130,
        publishId: 1,
        coverId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: 'We Love You, Charlie Freeman',
        authorId: 4,
        price: 141,
        publishId: 1,
        coverId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: 'Ethan Frome',
        authorId: 5,
        price: 200,
        publishId: 1,
        coverId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: 'Revolutionary Road',
        authorId: 6,
        price: 199,
        publishId: 2,
        coverId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: 'Empire Falls',
        authorId: 7,
        price: 299,
        publishId: 2,
        coverId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: 'Main',
        authorId: 8,
        price: 229,
        publishId: 2,
        coverId: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: 'Wintergirls',
        authorId: 9,
        price: 391,
        publishId: 2,
        coverId: 9,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: `The Pilot's Wife`,
        authorId: 10,
        price: 329,
        publishId: 2,
        coverId: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: 'Labor Day',
        authorId: 11,
        price: 419,
        publishId: 3,
        coverId: 11,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        name: 'On Beauty',
        authorId: 12,
        price: 311,
        publishId: 3,
        coverId: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        name: 'Faith',
        authorId: 13,
        price: 212,
        publishId: 3,
        coverId: 13,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        name: 'Hush, Hush',
        authorId: 14,
        price: 311,
        publishId: 3,
        coverId: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        name: 'Interpreter of Maladies',
        authorId: 15,
        price: 212,
        publishId: 3,
        coverId: 15,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        name: 'The Rules of Attraction',
        authorId: 16,
        price: 199,
        publishId: 4,
        coverId: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        name: 'Infinite Jest',
        authorId: 17,
        price: 299,
        publishId: 4,
        coverId: 17,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        name: 'Strong Motion',
        authorId: 18,
        price: 399,
        publishId: 4,
        coverId: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 19,
        name: 'Boy, Snow, Bird',
        authorId: 19,
        price: 400,
        publishId: 4,
        coverId: 19,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 20,
        name: 'The Bell Jar',
        authorId: 20,
        price: 229,
        publishId: 4,
        coverId: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]),

  down: async (queryInterface, Sequelize) =>
    await queryInterface.bulkDelete('Books', null, {}),
};
