'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.createTable('Books', [
      {
        name: 'The Boston Girl',
        author: 'Anita Diamant',
        genre: 'melodrama',
        price: 100,
        publishHouse: 'English hats',
        coverId: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'The Cider House Rules',
        author: 'John Irving',
        genre: 'romance',
        price: 121,
        publishHouse: 'English hats',
        coverId: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Olive Kitteridge',
        author: 'Elizabeth Strout',
        genre: 'drama',
        price: 130,
        publishHouse: 'English hats',
        coverId: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'We Love You, Charlie Freeman',
        author: 'Kaitlyn Greenidge',
        genre: 'psychological realism',
        price: 141,
        publishHouse: 'English hats',
        coverId: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Ethan Frome',
        author: 'Edith Wharton',
        genre: 'fantasy',
        price: 200,
        publishHouse: 'English hats',
        coverId: 5,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Revolutionary Road',
        author: 'Richard Yates',
        genre: 'romance',
        price: 199,
        publishHouse: 'Nipples production',
        coverId: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'Empire Falls',
        author: 'Richard Russo',
        genre: 'psychological realism',
        price: 299,
        publishHouse: 'Nipples production',
        coverId: 7,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 229,
      //   publishHouse: 'Nipples production',
      //   coverId: 8,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 391,
      //   publishHouse: 'Nipples production',
      //   coverId: 9,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 329,
      //   publishHouse: 'Nipples production',
      //   coverId: 10,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 419,
      //   publishHouse: 'what England is silent about',
      //   coverId: 11,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 311,
      //   publishHouse: 'what England is silent about',
      //   coverId: 12,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 212,
      //   publishHouse: 'what England is silent about',
      //   coverId: 13,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 311,
      //   publishHouse: 'what England is silent about',
      //   coverId: 14,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 212,
      //   publishHouse: 'what England is silent about',
      //   coverId: 15,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 199,
      //   publishHouse: 'tea with milk',
      //   coverId: 16,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 299,
      //   publishHouse: 'tea with milk',
      //   coverId: 17,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 399,
      //   publishHouse: 'tea with milk',
      //   coverId: 18,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 400,
      //   publishHouse: 'tea with milk',
      //   coverId: 19,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
      // {
      //   name: 'Zaglushka',
      //   author: 'Author',
      //   genre: 'Fantasy',
      //   price: 229,
      //   publishHouse: 'tea with milk',
      //   coverId: 20,
      //   createdAt: new Date(),
      //   updatedAt: new Date(),
      // },
    ]);
  },
  down: async (queryInterface, Sequelize) => {
    await queryInterface.dropTable('Books', null, {});
  },
};
